-- billing_05: allow vehicle_addon_charges.status = 'pending'.
-- Apply manually in the Supabase SQL editor, like the rls_* and billing_*
-- series. Safe to re-run: the whole change sits in a do-block that inspects the
-- catalogue first and does nothing when the constraint is already correct.
--
-- ORDER MATTERS: APPLY THIS BEFORE DEPLOYING THE CODE.
-- The reworked lib/billing/addonServer.ts writes a row with status 'pending'
-- BEFORE it calls Square. Against the un-widened constraint that insert is
-- rejected with 23514 (check_violation).
--
-- THIS ONE IS NOT A MONEY HAZARD, unlike billing_04's ordering warning, and an
-- operator should know that before deciding how to sequence a rollout. The
-- rejected insert happens BEFORE any Square call, so the request throws with no
-- payment attempted: no money moves, no card is touched, and the customer sees
-- an error and no vehicle added. The failure mode is a broken feature, not a
-- silent charge. Compare billing_04, where a missing function threw AFTER the
-- money had gone. Still apply this first, because "vehicles cannot be added"
-- is an outage; just do not panic about the till.
--
-- WHY 'pending' EXISTS AT ALL.
-- Square only replays a reused idempotency key when the request BODY is also
-- unchanged. The add-on body is not naturally stable: the amount derives from
-- the days remaining in the cycle (which drops by one at every London
-- midnight) and from the baseline fleet size (which moves whenever any other
-- vehicle is added), and the note interpolates the day count. So the old
-- "recompute the same key on retry and Square deduplicates" story was false.
-- A crash between a successful Square call and the audit insert left no row,
-- so the next request recomputed the same attempt but a DIFFERENT body, Square
-- answered IDEMPOTENCY_KEY_REUSED, and the code threw PAYMENT_INDETERMINATE
-- forever: the attempt number cannot advance without an audit row, and the
-- audit row cannot be written without a successful call. The customer was
-- charged, had no coverage, could not activate the vehicle, and when the cycle
-- eventually rolled over a fresh cycle_date minted a new key and charged them
-- a second time for a payment nothing had recorded.
--
-- The fix is to record intent first. The code inserts the row with status
-- 'pending' and the EXACT covers_days, baseline_count and amounts it is about
-- to send, then calls Square, then updates that same row to 'succeeded' or
-- 'failed'. A retry finds the pending row and rebuilds a byte-identical body
-- from the stored values, so the replay actually works and Square returns the
-- original payment instead of refusing the key.
--
-- WHAT A 'pending' ROW MEANS TO AN OPERATOR.
-- It is a payment whose outcome is UNKNOWN, not a payment that has not
-- happened. The card may well have been charged. Never read a pending row as
-- unpaid, and never delete one to "clean up": deleting it frees the attempt
-- number, and the next request would send a different body under the key that
-- pending row had already spent, which wedges the vehicle exactly the way this
-- migration exists to prevent.
--
-- Rows should leave 'pending' within seconds. Anything still pending after a
-- day is a crash that never got retried, and needs reconciling against Square's
-- payment list by idempotency key (the key format is in addonIdempotencyKey,
-- lib/billing/money.ts):
--
-- select * from public.vehicle_addon_charges
-- where status = 'pending' and created_at < now() - interval '1 day';
--
-- NOTHING ELSE READS THIS TABLE.
-- The only queries against vehicle_addon_charges are inside
-- lib/billing/addonServer.ts, and the one that decides "already paid" filters
-- on status = 'succeeded'. No page, view or report surfaces these rows today,
-- so widening the domain cannot make a pending row read as a paid one. If a
-- billing page ever starts listing this table, it must filter status
-- explicitly, or it will show an unknown-outcome charge as a completed one.
--
-- WHY A do-BLOCK RATHER THAN A PLAIN ALTER.
-- billing_03 declared the column with an INLINE check, so the constraint name
-- was generated by Postgres. The generated name is predictable in practice
-- ("vehicle_addon_charges_status_check") but it is NOT guaranteed: a table
-- restored, renamed, or created through another path can carry a different
-- name, and a hardcoded drop would then either error or, worse, silently drop
-- nothing if written with `if exists`, leaving the narrow constraint in place
-- and the deploy broken in a way this file appears to have fixed. So the name
-- is looked up from the catalogue by the COLUMN it constrains, not assumed.
--
-- ROLLBACK. Reverting the CODE is safe on its own and needs no SQL: the old
-- code never writes or reads 'pending', and leaving the wider domain in place
-- costs nothing. Any pending row left behind by the reverted code is then
-- stranded, so reconcile those against Square by hand (query above) before
-- assuming the revert is clean. Narrowing the domain back is optional and must
-- come last, because adding the old constraint VALIDATES existing rows and
-- errors out while any pending row survives:
--
--   alter table public.vehicle_addon_charges
--     drop constraint vehicle_addon_charges_status_check;
--   alter table public.vehicle_addon_charges
--     add constraint vehicle_addon_charges_status_check
--     check (status in ('succeeded', 'failed'));
--
-- That failure is the constraint doing its job. Do not force it with `not
-- valid`: an unvalidated constraint would leave the pending rows in place and
-- hide them behind a domain that claims they cannot exist.

do $$
declare
  v_status_attnum smallint;
  v_already_correct boolean;
  r record;
begin
  -- The attnum of the status column, used to find the check constraints that
  -- actually key on it. Matching on the constraint TEXT instead would be
  -- fragile in both directions: it would miss a multi-column check and it
  -- would match an unrelated constraint that merely mentions the word.
  select a.attnum
    into v_status_attnum
  from pg_attribute a
  where a.attrelid = 'public.vehicle_addon_charges'::regclass
    and a.attname = 'status'
    and not a.attisdropped;

  if v_status_attnum is null then
    raise exception 'public.vehicle_addon_charges has no status column; apply billing_03 first';
  end if;

  -- Idempotence check: is there already a check constraint on status that
  -- permits 'pending'? If so this file has been applied and there is nothing
  -- to do. Re-running must not drop and recreate, because between the drop and
  -- the add the table would briefly accept any status at all.
  select exists (
    select 1
    from pg_constraint c
    where c.conrelid = 'public.vehicle_addon_charges'::regclass
      and c.contype = 'c'
      and c.conkey @> array[v_status_attnum]
      and pg_get_constraintdef(c.oid) ilike '%pending%'
  ) into v_already_correct;

  if v_already_correct then
    raise notice 'billing_05: status already allows pending, nothing to do';
    return;
  end if;

  -- Drop every check constraint keyed on status, whatever it is called. There
  -- is exactly one today (billing_03's inline check). Looping rather than
  -- dropping a single looked-up name means a hand-added second constraint
  -- cannot survive and quietly keep rejecting 'pending' after this file
  -- reports success.
  for r in
    select c.conname, pg_get_constraintdef(c.oid) as def
    from pg_constraint c
    where c.conrelid = 'public.vehicle_addon_charges'::regclass
      and c.contype = 'c'
      and c.conkey @> array[v_status_attnum]
  loop
    raise notice 'billing_05: dropping % (%)', r.conname, r.def;
    execute format(
      'alter table public.vehicle_addon_charges drop constraint %I',
      r.conname
    );
  end loop;

  -- Named explicitly this time, so the next migration that needs to touch it
  -- can drop it by name instead of repeating this lookup. The domain stays
  -- closed: three known values, so a typo in application code is still a 23514
  -- rather than a row nobody can interpret.
  alter table public.vehicle_addon_charges
    add constraint vehicle_addon_charges_status_check
    check (status in ('pending', 'succeeded', 'failed'));

  raise notice 'billing_05: status now allows pending, succeeded, failed';
end $$;

-- VERIFY. Expect exactly one row, whose definition lists all three values.
--
--   select c.conname, pg_get_constraintdef(c.oid)
--   from pg_constraint c
--   where c.conrelid = 'public.vehicle_addon_charges'::regclass
--     and c.contype = 'c'
--     and pg_get_constraintdef(c.oid) ilike '%status%';
--
-- And a live smoke test of the thing that matters, which must succeed and then
-- leave nothing behind:
--
--   begin;
--   insert into public.vehicle_addon_charges (
--     company_id, vehicle_id, cycle_date, attempt, covers_days, baseline_count,
--     net_pence, vat_pence, gross_pence, status
--   )
--   select company_id, vehicle_id, cycle_date, 999, covers_days, baseline_count,
--          net_pence, vat_pence, gross_pence, 'pending'
--   from public.vehicle_addon_charges limit 1;
--   rollback;
--
-- (Skip it on an empty table; there is nothing to copy a valid company_id and
-- vehicle_id from, and the foreign keys will refuse an invented one.)
--
-- WHAT BREAKS IF THIS IS NOT APPLIED BEFORE THE DEPLOY.
-- Every mid-cycle vehicle addition fails with 23514 on the intent insert,
-- surfaced to the customer as a 500 from /api/licences/activate. No payment is
-- attempted, no coverage is written, no licence is activated. Apply this file
-- and the next attempt works; there is nothing to reconcile.
