-- prodfix_33: platform billing integrity (claims, intents, guards).
-- Apply manually in the Supabase SQL editor, like the billing_* series.
-- Safe to re-run: every change is guarded or `create or replace`.
--
-- Findings (docs/superpowers/reviews/2026-09-14-production-readiness-review.md):
--
--   BILL2-2   two collectors could charge one closed or failed period twice.
--             STEP 1 adds a database claim on collection.
--   BILL2-15  a cooling-off refund Square had not completed was recorded as
--             refunded. STEP 2 adds period_charges.status 'refund_pending'.
--   BILL2-2   STEP 3 is the backstop: at most one succeeded, non-zero charge of
--             each kind per period.
--   BILL2-18  a declined up-front minimum deleted its own period and, through
--             the cascade, its failed charge row. STEP 4 lets the period be
--             kept as closed_reason 'minimum_declined' instead.
--   BILL2-17  re-opening a period on the day an earlier one started collided
--             on unique (company_id, period_start). STEP 5 narrows that rule
--             to periods that actually billed.
--   BILL2-1, BILL2-6, BILL2-20
--             the spec's ensure_open_billing_period guards never existed.
--             STEP 6 enforces them on the table: no open period for a company
--             that is not active, and none while another period is unpaid.
--   BILL1-3, BILL1-6
--             a v1 cycle charge with an unrecorded outcome wedged forever once
--             the fleet changed, because nothing stored the request body.
--             STEP 7 lets platform_charges hold a 'pending' intent (amounts,
--             card and the vehicle ids it pays for) and makes
--             record_cycle_charge SETTLE that row instead of skipping it.
--   BILL2-10  the cooling-off refund was once per company only. STEP 8 stores
--             the card fingerprint so it can be once per card too.
--
-- ORDER.
--
--   * Apply this BEFORE docs/sql/prodfix_31_billing_evidence_retention.sql.
--     prodfix_31 makes period_charges -> billing_periods ON DELETE RESTRICT.
--     Without STEP 4 here, the code's fallback for a declined minimum is to
--     delete the period, which RESTRICT then refuses, and the customer sees an
--     error (no money moves: the decline already happened, nothing is charged
--     again).
--   * The code may deploy before or after this file. Every path degrades to
--     the behaviour that exists today, never to a silent charge:
--       - no claim function: collection runs unclaimed, and the new
--         "already succeeded" check in periodPaymentServer.ts still refuses a
--         second charge;
--       - platform_charges without 'pending': runChargeCycle records no intent
--         and records the outcome after Square answers, as before;
--       - no 'refund_pending': a pending refund is recorded as refunded with
--         failure_code REFUND_PENDING_AT_SQUARE;
--       - no 'minimum_declined': the declined period is deleted, as before;
--       - no card_fingerprint: the per-card cooling-off check is skipped.
--
-- LIVE-STATE DEPENDENCIES. Constraint names below were generated by Postgres
-- from inline declarations in billing_01 and billing_06, so they are FOUND IN
-- THE CATALOGUE by the columns they constrain, never assumed. The role name
-- service_role is the one billing_04 already grants to.
--
-- NOTHING HERE WIDENS ACCESS. No policy changes, no grants to anon or
-- authenticated. New functions are executable by service_role only. The new
-- trigger is invoker-rights and only raises.

begin;

-- ===========================================================================
-- STEP 1: claim a period for collection (BILL2-2).
-- ===========================================================================
--
-- Computing a period was already claimed (open -> closing). Collecting one that
-- was already closed or failed was not: two runs holding a stale snapshot both
-- charged it, the second under a NEW attempt number, which is a new idempotency
-- key, which Square treats as a new payment.
--
-- The claim is a conditional update on (status, attempt_count, marker), so it
-- succeeds for exactly one caller. A claim older than p_stale_minutes is
-- considered abandoned by a crashed run and may be taken over; that is safe
-- because the charge path replays a pending row under its original key rather
-- than minting a new one. The collecting run clears the marker when it writes
-- the outcome.
alter table public.billing_periods
  add column if not exists collecting_since timestamptz;

comment on column public.billing_periods.collecting_since is
  'Set while a run is charging this period. Cleared when the outcome is written. See claim_billing_period_collection.';

create or replace function public.claim_billing_period_collection(
  p_period_id uuid,
  p_expected_attempt_count int,
  p_stale_minutes int
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id uuid;
begin
  update public.billing_periods
     set collecting_since = now()
   where id = p_period_id
     and status in ('closed', 'failed')
     and attempt_count = p_expected_attempt_count
     and (
       collecting_since is null
       or collecting_since < now() - make_interval(mins => greatest(coalesce(p_stale_minutes, 15), 1))
     )
  returning id into v_id;

  return v_id is not null;
end $$;

revoke all on function public.claim_billing_period_collection(uuid, int, int)
  from public, anon, authenticated;
grant execute on function public.claim_billing_period_collection(uuid, int, int)
  to service_role;

-- ===========================================================================
-- STEP 2: period_charges.status allows 'refund_pending' (BILL2-15).
-- ===========================================================================
do $$
declare
  v_attnum smallint;
  v_all_permit boolean := true;
  v_any boolean := false;
  v_permits boolean;
  r record;
begin
  select attnum into v_attnum from pg_attribute
  where attrelid = 'public.period_charges'::regclass and attname = 'status' and not attisdropped;

  for r in
    select c.conname, pg_get_expr(c.conbin, c.conrelid) as expr
    from pg_constraint c
    where c.conrelid = 'public.period_charges'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    v_any := true;
    begin
      execute format('select (%s) is not false from (select %L::text as status) t', r.expr, 'refund_pending')
        into v_permits;
    exception when others then
      v_permits := false;
    end;
    if not v_permits then v_all_permit := false; end if;
  end loop;

  if v_any and v_all_permit then
    raise notice 'prodfix_33: period_charges.status already allows refund_pending';
    return;
  end if;

  for r in
    select c.conname from pg_constraint c
    where c.conrelid = 'public.period_charges'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    execute format('alter table public.period_charges drop constraint %I', r.conname);
  end loop;

  alter table public.period_charges
    add constraint period_charges_status_check
    check (status in ('pending', 'succeeded', 'failed', 'refunded', 'refund_pending'));
  raise notice 'prodfix_33: period_charges.status now allows refund_pending';
end $$;

-- ===========================================================================
-- STEP 3: at most one succeeded, non-zero charge of each kind per period.
-- ===========================================================================
--
-- The database backstop for BILL2-2. Zero-amount settled rows are excluded:
-- they record "nothing was owed" and a period can legitimately carry more than
-- one (a declined attempt that later recomputes to zero). Skipped with a notice
-- if duplicates already exist, because those are double charges to refund by
-- hand, and creating the index would fail the whole file.
do $$
begin
  if exists (
    select 1 from public.period_charges
    where status = 'succeeded' and gross_pence > 0
    group by billing_period_id, kind having count(*) > 1
  ) then
    raise notice 'prodfix_33: DUPLICATE succeeded period charges exist; index NOT created. Reconcile these first: select billing_period_id, kind, count(*) from public.period_charges where status = ''succeeded'' and gross_pence > 0 group by 1, 2 having count(*) > 1;';
  else
    execute 'create unique index if not exists period_charges_one_success
               on public.period_charges (billing_period_id, kind)
               where status = ''succeeded'' and gross_pence > 0';
  end if;
end $$;

-- ===========================================================================
-- STEP 4: closed_reason allows 'minimum_declined' (BILL2-18).
-- ===========================================================================
do $$
declare
  v_attnum smallint;
  v_all_permit boolean := true;
  v_any boolean := false;
  v_permits boolean;
  r record;
begin
  select attnum into v_attnum from pg_attribute
  where attrelid = 'public.billing_periods'::regclass and attname = 'closed_reason' and not attisdropped;

  for r in
    select c.conname, pg_get_expr(c.conbin, c.conrelid) as expr
    from pg_constraint c
    where c.conrelid = 'public.billing_periods'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    v_any := true;
    begin
      execute format('select (%s) is not false from (select %L::text as closed_reason) t', r.expr, 'minimum_declined')
        into v_permits;
    exception when others then
      v_permits := false;
    end;
    if not v_permits then v_all_permit := false; end if;
  end loop;

  if v_any and v_all_permit then
    raise notice 'prodfix_33: closed_reason already allows minimum_declined';
    return;
  end if;

  for r in
    select c.conname from pg_constraint c
    where c.conrelid = 'public.billing_periods'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    execute format('alter table public.billing_periods drop constraint %I', r.conname);
  end loop;

  alter table public.billing_periods
    add constraint billing_periods_closed_reason_check
    check (closed_reason in ('scheduled', 'cancellation', 'cooling_off', 'minimum_declined'));
  raise notice 'prodfix_33: closed_reason now allows minimum_declined';
end $$;

comment on column public.billing_periods.closed_reason is
  'scheduled, cancellation, cooling_off, or minimum_declined (the up-front minimum was refused, nothing was billed, the row is kept as the audit trail of the attempt).';

-- ===========================================================================
-- STEP 5: one BILLING period per company start date (BILL2-17).
-- ===========================================================================
--
-- billing_06's unique (company_id, period_start) also counted periods that
-- billed nothing: a cooling-off refund, a cancellation, a declined minimum.
-- Re-opening on that same London day then collided and the customer got a
-- generic 500 for the rest of the day. The rule that matters, never two
-- billable periods from one date, is kept as a partial unique index. The new
-- index is built BEFORE the old constraint is dropped, so there is no moment
-- without the rule.
create unique index if not exists billing_periods_company_start_billable
  on public.billing_periods (company_id, period_start)
  where coalesce(closed_reason, 'scheduled') not in ('cooling_off', 'cancellation', 'minimum_declined');

do $$
declare
  v_company smallint;
  v_start smallint;
  r record;
begin
  select attnum into v_company from pg_attribute
  where attrelid = 'public.billing_periods'::regclass and attname = 'company_id' and not attisdropped;
  select attnum into v_start from pg_attribute
  where attrelid = 'public.billing_periods'::regclass and attname = 'period_start' and not attisdropped;

  for r in
    select c.conname from pg_constraint c
    where c.conrelid = 'public.billing_periods'::regclass
      and c.contype = 'u'
      and c.conkey @> array[v_company, v_start]
      and array_length(c.conkey, 1) = 2
  loop
    execute format('alter table public.billing_periods drop constraint %I', r.conname);
    raise notice 'prodfix_33: dropped % in favour of billing_periods_company_start_billable', r.conname;
  end loop;
end $$;

-- ===========================================================================
-- STEP 6: refuse to open a period the spec says must not exist.
-- ===========================================================================
--
-- The spec relies on an ensure_open_billing_period function "that refuses to
-- open a new period while one is failed" and "opens no successor" for a
-- cancelled company. It was never created (BILL2-20), and those missing guards
-- were BILL2-1 (a cancelled company billed every 28 days) and BILL2-6 (a
-- failing company opened a fresh period). The application now checks both;
-- this is the layer that holds if a code path forgets.
--
-- Only an OPENING is judged: an insert of an open period, or an update that
-- moves a period INTO open. Updates to an already-open period (prepaid, a
-- shortened end on cancellation) pass untouched.
--
-- Invoker rights: it reads company_billing and billing_periods, which the
-- service role can read, and it only raises.
create or replace function public.guard_billing_period_open()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_status text;
begin
  if new.status::text <> 'open' then
    return new;
  end if;
  if tg_op = 'UPDATE' and old.status::text = 'open' then
    return new;
  end if;

  select cb.status into v_status
  from public.company_billing cb
  where cb.company_id = new.company_id;

  if v_status is distinct from 'active' then
    raise exception 'A billing period cannot be opened for company % while its billing status is %.',
        new.company_id, coalesce(v_status, 'missing')
      using errcode = 'BIL01', hint = 'billing_period_company_not_active';
  end if;

  if exists (
    select 1 from public.billing_periods p
    where p.company_id = new.company_id
      and p.id <> new.id
      and p.status::text in ('closing', 'closed', 'failed')
  ) then
    raise exception 'A billing period cannot be opened for company % while an earlier period is unpaid.',
        new.company_id
      using errcode = 'BIL01', hint = 'billing_period_unpaid';
  end if;

  return new;
end $$;

revoke all on function public.guard_billing_period_open() from public, anon, authenticated;

drop trigger if exists guard_billing_period_open on public.billing_periods;
create trigger guard_billing_period_open
  before insert or update of status on public.billing_periods
  for each row execute function public.guard_billing_period_open();

-- ===========================================================================
-- STEP 7: v1 cycle charges record intent first (BILL1-3, BILL1-6).
-- ===========================================================================
--
-- The same fix billing_05 made for add-ons and billing_06 built into
-- period_charges. The pending row stores what was sent to Square (amounts, the
-- card, and the vehicle ids the charge pays for), so a retry after a crash or
-- an indeterminate answer resends a byte-identical body under the same key and
-- Square replays the original payment. A dunning retry charges the amount the
-- cycle RECORDED rather than re-pricing today's fleet.
--
-- A pending row is an UNKNOWN outcome, not an unpaid one. Never delete one.
do $$
declare
  v_attnum smallint;
  v_all_permit boolean := true;
  v_any boolean := false;
  v_permits boolean;
  r record;
begin
  select attnum into v_attnum from pg_attribute
  where attrelid = 'public.platform_charges'::regclass and attname = 'status' and not attisdropped;

  for r in
    select c.conname, pg_get_expr(c.conbin, c.conrelid) as expr
    from pg_constraint c
    where c.conrelid = 'public.platform_charges'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    v_any := true;
    begin
      execute format('select (%s) is not false from (select %L::text as status) t', r.expr, 'pending')
        into v_permits;
    exception when others then
      v_permits := false;
    end;
    if not v_permits then v_all_permit := false; end if;
  end loop;

  if v_any and v_all_permit then
    raise notice 'prodfix_33: platform_charges.status already allows pending';
    return;
  end if;

  for r in
    select c.conname from pg_constraint c
    where c.conrelid = 'public.platform_charges'::regclass
      and c.contype = 'c' and c.conkey @> array[v_attnum]
  loop
    execute format('alter table public.platform_charges drop constraint %I', r.conname);
  end loop;

  alter table public.platform_charges
    add constraint platform_charges_status_check
    check (status in ('pending', 'succeeded', 'failed'));
  raise notice 'prodfix_33: platform_charges.status now allows pending';
end $$;

alter table public.platform_charges add column if not exists square_card_id text;
alter table public.platform_charges add column if not exists square_customer_id text;
alter table public.platform_charges add column if not exists vehicle_ids uuid[];

comment on column public.platform_charges.vehicle_ids is
  'Vehicles this cycle charge pays for, snapshotted when the intent is recorded. Coverage is written from this, not from the live fleet.';

create index if not exists platform_charges_pending_idx
  on public.platform_charges (company_id, cycle_date)
  where status = 'pending';

-- Same signature as billing_04, so existing grants carry over under
-- `create or replace`; they are restated below anyway.
--
-- CHANGED: a conflict with a PENDING row for the same attempt now settles it
-- (status, payment id, receipt, failure code). The amounts stored on the
-- pending row are kept: they are what the idempotency key bought. A conflict
-- with an already settled row still changes nothing, which keeps the replay
-- after a crash idempotent. Coverage is written only when the row for this
-- attempt is succeeded after the upsert, so a late caller cannot write
-- coverage against a row that settled as failed.
create or replace function public.record_cycle_charge(
  p_company_id uuid,
  p_cycle_date date,
  p_attempt int,
  p_vehicle_count int,
  p_net_pence bigint,
  p_vat_pence bigint,
  p_gross_pence bigint,
  p_vat_rate numeric,
  p_currency text,
  p_square_payment_id text,
  p_receipt_url text,
  p_status text,
  p_failure_code text,
  p_vehicle_ids uuid[]
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.platform_charges (
    company_id, cycle_date, attempt, vehicle_count,
    net_pence, vat_pence, gross_pence, vat_rate, currency,
    square_payment_id, receipt_url, status, failure_code
  )
  values (
    p_company_id, p_cycle_date, p_attempt, p_vehicle_count,
    p_net_pence, p_vat_pence, p_gross_pence, p_vat_rate, p_currency,
    p_square_payment_id, p_receipt_url, p_status, p_failure_code
  )
  on conflict (company_id, cycle_date, attempt) do update
    set status = excluded.status,
        square_payment_id = excluded.square_payment_id,
        receipt_url = excluded.receipt_url,
        failure_code = excluded.failure_code
    where public.platform_charges.status = 'pending';

  if p_status = 'succeeded' and exists (
    select 1 from public.platform_charges
    where company_id = p_company_id
      and cycle_date = p_cycle_date
      and attempt = p_attempt
      and status = 'succeeded'
  ) then
    insert into public.vehicle_cycle_coverage (company_id, cycle_date, vehicle_id)
    select p_company_id, p_cycle_date, vid
    from unnest(coalesce(p_vehicle_ids, '{}'::uuid[])) as vid
    on conflict (company_id, cycle_date, vehicle_id) do nothing;
  end if;
end $$;

revoke all on function public.record_cycle_charge(
  uuid, date, int, int, bigint, bigint, bigint, numeric,
  text, text, text, text, text, uuid[]
) from public, anon, authenticated;

grant execute on function public.record_cycle_charge(
  uuid, date, int, int, bigint, bigint, bigint, numeric,
  text, text, text, text, text, uuid[]
) to service_role;

-- ===========================================================================
-- STEP 8: card fingerprint for the per-card cooling-off rule (BILL2-10).
-- ===========================================================================
--
-- Square's Card.fingerprint identifies the card number across customers, which
-- is what stops a new company name on the same card getting a second refund.
-- Written by /api/billing/card on every save. Not a secret: it cannot be turned
-- back into a card number, and company_billing is readable only by the
-- company's own admins (billing_01).
alter table public.company_billing add column if not exists card_fingerprint text;

create index if not exists company_billing_card_fingerprint_idx
  on public.company_billing (card_fingerprint)
  where card_fingerprint is not null;

commit;

-- ===========================================================================
-- VERIFY. Every row must say PASS.
-- ===========================================================================
select 'claim function is service_role only' as probe,
       case when has_function_privilege('authenticated', 'public.claim_billing_period_collection(uuid, int, int)', 'execute')
            then 'FAIL' else 'PASS' end as outcome
union all
select 'period_charges accepts refund_pending',
       case when exists (
         select 1 from pg_constraint
         where conrelid = 'public.period_charges'::regclass and contype = 'c'
           and pg_get_constraintdef(oid) ilike '%refund_pending%') then 'PASS' else 'FAIL' end
union all
select 'one succeeded charge per period and kind',
       case when exists (select 1 from pg_indexes where indexname = 'period_charges_one_success')
            then 'PASS' else 'FAIL (see the notice about duplicates)' end
union all
select 'closed_reason accepts minimum_declined',
       case when exists (
         select 1 from pg_constraint
         where conrelid = 'public.billing_periods'::regclass and contype = 'c'
           and pg_get_constraintdef(oid) ilike '%minimum_declined%') then 'PASS' else 'FAIL' end
union all
select 'old unique (company_id, period_start) is gone',
       case when exists (
         select 1 from pg_constraint
         where conrelid = 'public.billing_periods'::regclass and contype = 'u'
           and pg_get_constraintdef(oid) ilike '%(company_id, period_start)%') then 'FAIL' else 'PASS' end
union all
select 'billable start-date index exists',
       case when exists (select 1 from pg_indexes where indexname = 'billing_periods_company_start_billable')
            then 'PASS' else 'FAIL' end
union all
select 'open-period guard trigger installed',
       case when exists (
         select 1 from pg_trigger where tgname = 'guard_billing_period_open' and not tgisinternal)
            then 'PASS' else 'FAIL' end
union all
select 'platform_charges accepts pending',
       case when exists (
         select 1 from pg_constraint
         where conrelid = 'public.platform_charges'::regclass and contype = 'c'
           and pg_get_constraintdef(oid) ilike '%pending%') then 'PASS' else 'FAIL' end
union all
select 'platform_charges intent columns',
       case when (select count(*) from information_schema.columns
                  where table_schema = 'public' and table_name = 'platform_charges'
                    and column_name in ('square_card_id', 'square_customer_id', 'vehicle_ids')) = 3
            then 'PASS' else 'FAIL' end
union all
select 'record_cycle_charge not executable by authenticated',
       case when has_function_privilege('authenticated',
              'public.record_cycle_charge(uuid, date, int, int, bigint, bigint, bigint, numeric, text, text, text, text, text, uuid[])',
              'execute') then 'FAIL' else 'PASS' end
union all
select 'company_billing.card_fingerprint',
       case when exists (select 1 from information_schema.columns
                         where table_schema = 'public' and table_name = 'company_billing'
                           and column_name = 'card_fingerprint') then 'PASS' else 'FAIL' end;
