/* The customer row as /api/customers returns it. Lives here rather than in
   page.tsx so CustomerCard can import it without importing a route module. */
export type Customer = {
  id: string;
  name: string;
  legal_name: string | null;
  trading_name: string | null;
  account_code: string | null;
  company_number: string | null;
  vat_number: string | null;
  eori_number: string | null;
  website: string | null;
  industry_type: string | null;
  active: boolean;
  contact_name: string | null;
  job_title: string | null;
  phone: string | null;
  mobile: string | null;
  email: string | null;
  accounts_email: string | null;
  operations_email: string | null;
  address_line_1: string | null;
  address_line_2: string | null;
  city: string | null;
  county_region: string | null;
  postcode: string | null;
  country_code: string | null;
  payment_terms_days: number | null;
  credit_limit: number | null;
  credit_status: string | null;
  currency_code: string | null;
  requires_po: boolean;
  default_po_reference: string | null;
  fuel_surcharge_percent: number | null;
  vat_rate: number | null;
  default_collection_instructions: string | null;
  default_delivery_instructions: string | null;
  default_vehicle_type: string | null;
  tail_lift_required: boolean;
  adr_required: boolean;
  temperature_control_required: boolean;
  timed_delivery_required: boolean;
  pod_required: boolean;
  invoice_pod_attachment_required: boolean;
  pallet_exchange_required: boolean;
  weekend_delivery_allowed: boolean;
  booking_reference_required: boolean;
  default_depot: string | null;
  default_contact_method: string | null;
  account_manager: string | null;
  service_level: string | null;
  customer_status: string | null;
  credit_hold: boolean;
  out_of_hours_contact: string | null;
  external_customer_id: string | null;
  accounting_customer_id: string | null;
  crm_customer_id: string | null;
  api_enabled: boolean;
  webhook_url: string | null;
  notes: string | null;
};
