-- Multi-job van load manifests.
-- Application/service-role APIs are authoritative for writes.
-- Authenticated clients receive tenant-scoped read access only.

create table public.load_manifests (
  id uuid primary key default gen_random_uuid(),
  manifest_number bigint generated by default as identity unique,
  barcode_token uuid not null default gen_random_uuid() unique,

  tenant_id uuid not null,
  vehicle_id uuid not null references public.vehicles(id) on delete restrict,
  driver_id uuid not null references public.drivers(id) on delete restrict,

  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index load_manifests_tenant_idx
  on public.load_manifests(tenant_id);

create index load_manifests_vehicle_idx
  on public.load_manifests(vehicle_id);

create index load_manifests_driver_idx
  on public.load_manifests(driver_id);

create table public.load_manifest_items (
  id uuid primary key default gen_random_uuid(),

  tenant_id uuid not null,
  manifest_id uuid not null
    references public.load_manifests(id) on delete cascade,

  job_id uuid not null
    references public.jobs(id) on delete restrict,

  job_item_id uuid not null
    references public.job_items(id) on delete restrict,

  serial_number text not null,

  created_at timestamptz not null default now(),

  constraint load_manifest_items_serial_check
    check (
      length(btrim(serial_number)) between 1 and 250
      and serial_number = btrim(serial_number)
    )
);

create unique index load_manifest_items_manifest_serial_uidx
  on public.load_manifest_items(
    manifest_id,
    job_item_id,
    serial_number
  );

create index load_manifest_items_tenant_idx
  on public.load_manifest_items(tenant_id);

create index load_manifest_items_job_idx
  on public.load_manifest_items(job_id);

create index load_manifest_items_job_item_idx
  on public.load_manifest_items(job_item_id);

create table public.load_scan_events (
  id uuid primary key default gen_random_uuid(),

  tenant_id uuid not null,

  manifest_id uuid not null
    references public.load_manifests(id) on delete restrict,

  event_type text not null
    check (event_type in ('loaded', 'unloaded')),

  vehicle_id uuid not null
    references public.vehicles(id) on delete restrict,

  driver_id uuid not null
    references public.drivers(id) on delete restrict,

  stop_id uuid
    references public.job_stops(id) on delete restrict,

  scanned_by uuid not null
    references auth.users(id) on delete restrict,

  latitude double precision,
  longitude double precision,
  accuracy_m double precision,

  scanned_at timestamptz not null default now(),

  constraint load_scan_events_latitude_check
    check (
      latitude is null
      or latitude between -90 and 90
    ),

  constraint load_scan_events_longitude_check
    check (
      longitude is null
      or longitude between -180 and 180
    ),

  constraint load_scan_events_accuracy_check
    check (
      accuracy_m is null
      or accuracy_m >= 0
    )
);

create index load_scan_events_manifest_time_idx
  on public.load_scan_events(manifest_id, scanned_at, id);

create index load_scan_events_tenant_idx
  on public.load_scan_events(tenant_id);

create index load_scan_events_vehicle_idx
  on public.load_scan_events(vehicle_id);

create index load_scan_events_driver_idx
  on public.load_scan_events(driver_id);

alter table public.load_manifests
  enable row level security;

alter table public.load_manifest_items
  enable row level security;

alter table public.load_scan_events
  enable row level security;

create policy load_manifests_select_tenant
  on public.load_manifests
  for select
  to authenticated
  using (
    tenant_id = auth_tenant_id()
  );

create policy load_manifest_items_select_tenant
  on public.load_manifest_items
  for select
  to authenticated
  using (
    tenant_id = auth_tenant_id()
  );

create policy load_scan_events_select_tenant
  on public.load_scan_events
  for select
  to authenticated
  using (
    tenant_id = auth_tenant_id()
  );

grant select
  on public.load_manifests
  to authenticated;

grant select
  on public.load_manifest_items
  to authenticated;

grant select
  on public.load_scan_events
  to authenticated;

grant usage, select
  on sequence public.load_manifests_manifest_number_seq
  to service_role;

-- Atomic creation of a multi-job serialized van manifest.
-- This function is intentionally callable by service_role only.
create or replace function public.create_load_manifest(
  p_tenant_id uuid,
  p_vehicle_id uuid,
  p_driver_id uuid,
  p_created_by uuid,
  p_items jsonb
)
returns table (
  manifest_id uuid,
  manifest_number bigint,
  barcode_token uuid,
  item_count integer,
  job_count integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_manifest_id uuid;
  v_manifest_number bigint;
  v_barcode_token uuid;
  v_item_count integer;
  v_job_count integer;
begin
  if p_tenant_id is null
     or p_vehicle_id is null
     or p_driver_id is null
     or p_created_by is null then
    raise exception 'Manifest identity fields are required.'
      using errcode = '22023';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'A load manifest requires at least one serialized item.'
      using errcode = '22023';
  end if;

  -- Lock the authoritative vehicle and driver rows while validating ownership.
  perform 1
  from public.vehicles v
  where v.id = p_vehicle_id
    and v.tenant_id = p_tenant_id
  for key share;

  if not found then
    raise exception 'Vehicle does not belong to this tenant.'
      using errcode = '23503';
  end if;

  perform 1
  from public.drivers d
  where d.id = p_driver_id
    and d.tenant_id = p_tenant_id
  for key share;

  if not found then
    raise exception 'Driver does not belong to this tenant.'
      using errcode = '23503';
  end if;

  create temporary table tmp_load_manifest_items (
    job_id uuid not null,
    job_item_id uuid not null,
    serial_number text not null
  ) on commit drop;

  begin
    insert into tmp_load_manifest_items (
      job_id,
      job_item_id,
      serial_number
    )
    select
      nullif(btrim(item ->> 'job_id'), '')::uuid,
      nullif(btrim(item ->> 'job_item_id'), '')::uuid,
      btrim(coalesce(item ->> 'serial_number', ''))
    from jsonb_array_elements(p_items) as item;
  exception
    when invalid_text_representation then
      raise exception 'Manifest contains an invalid job or item identifier.'
        using errcode = '22023';
  end;

  if exists (
    select 1
    from tmp_load_manifest_items
    where job_id is null
       or job_item_id is null
       or length(serial_number) not between 1 and 250
  ) then
    raise exception 'Every manifest item requires a valid job, item and serial number.'
      using errcode = '22023';
  end if;

  if (
    select count(*)
    from tmp_load_manifest_items
  ) <> jsonb_array_length(p_items) then
    raise exception 'Manifest item payload could not be parsed completely.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from tmp_load_manifest_items
    group by job_item_id, serial_number
    having count(*) > 1
  ) then
    raise exception 'The manifest contains a duplicate serialized item.'
      using errcode = '23505';
  end if;

  -- Every job in the manifest must belong to this tenant and be assigned to
  -- the same vehicle and driver as the manifest.
  if exists (
    select 1
    from (
      select distinct t.job_id
      from tmp_load_manifest_items t
    ) requested
    left join public.jobs j
      on j.id = requested.job_id
     and j.tenant_id = p_tenant_id
    where j.id is null
       or j.vehicle_id is distinct from p_vehicle_id
       or j.driver_id is distinct from p_driver_id
  ) then
    raise exception 'Every manifest job must belong to this tenant and be assigned to the manifest vehicle and driver.'
      using errcode = '23514';
  end if;

  -- Lock referenced job items so their serialized identity cannot disappear
  -- while the snapshot is being created.
  perform ji.id
  from public.job_items ji
  join (
    select distinct job_item_id
    from tmp_load_manifest_items
  ) requested
    on requested.job_item_id = ji.id
  where ji.tenant_id = p_tenant_id
  for key share;

  -- Validate item ownership, item-to-job relationship and exact serial
  -- membership inside job_items.serial_numbers.
  if exists (
    select 1
    from tmp_load_manifest_items t
    left join public.job_items ji
      on ji.id = t.job_item_id
     and ji.tenant_id = p_tenant_id
     and ji.job_id = t.job_id
    where ji.id is null
       or not (
         t.serial_number = any(
           coalesce(ji.serial_numbers, array[]::text[])
         )
       )
  ) then
    raise exception 'A manifest serial does not belong to the supplied tenant, job or job item.'
      using errcode = '23514';
  end if;

  insert into public.load_manifests (
    tenant_id,
    vehicle_id,
    driver_id,
    created_by
  )
  values (
    p_tenant_id,
    p_vehicle_id,
    p_driver_id,
    p_created_by
  )
  returning
    id,
    load_manifests.manifest_number,
    load_manifests.barcode_token
  into
    v_manifest_id,
    v_manifest_number,
    v_barcode_token;

  insert into public.load_manifest_items (
    tenant_id,
    manifest_id,
    job_id,
    job_item_id,
    serial_number
  )
  select
    p_tenant_id,
    v_manifest_id,
    t.job_id,
    t.job_item_id,
    t.serial_number
  from tmp_load_manifest_items t;

  select count(*)::integer
  into v_item_count
  from tmp_load_manifest_items;

  select count(distinct t.job_id)::integer
  into v_job_count
  from tmp_load_manifest_items t;

  return query
  select
    v_manifest_id,
    v_manifest_number,
    v_barcode_token,
    v_item_count,
    v_job_count;
end;
$function$;


-- Atomic ON/OFF-van state transition.
-- The caller must authenticate the driver and active vehicle assignment first.
create or replace function public.record_load_manifest_event(
  p_tenant_id uuid,
  p_barcode_token uuid,
  p_driver_id uuid,
  p_vehicle_id uuid,
  p_scanned_by uuid,
  p_action text,
  p_stop_id uuid default null,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_m double precision default null
)
returns table (
  manifest_id uuid,
  manifest_number bigint,
  event_id uuid,
  event_type text,
  manifest_state text,
  item_count integer,
  job_count integer,
  scanned_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_manifest public.load_manifests%rowtype;
  v_latest_event_type text;
  v_event_id uuid;
  v_event_type text;
  v_scanned_at timestamptz;
  v_item_count integer;
  v_job_count integer;
  v_active_assignment_count integer;
  v_matching_assignment_count integer;
begin
  if p_tenant_id is null
     or p_barcode_token is null
     or p_driver_id is null
     or p_vehicle_id is null
     or p_scanned_by is null then
    raise exception 'Manifest scan identity fields are required.'
      using errcode = '22023';
  end if;

  if p_action not in ('load', 'unload') then
    raise exception 'Manifest action must be load or unload.'
      using errcode = '22023';
  end if;

  if p_latitude is not null
     and (p_latitude < -90 or p_latitude > 90) then
    raise exception 'Latitude is outside the valid range.'
      using errcode = '22023';
  end if;

  if p_longitude is not null
     and (p_longitude < -180 or p_longitude > 180) then
    raise exception 'Longitude is outside the valid range.'
      using errcode = '22023';
  end if;

  if p_accuracy_m is not null
     and p_accuracy_m < 0 then
    raise exception 'GPS accuracy cannot be negative.'
      using errcode = '22023';
  end if;

  -- Serialize all state changes for this manifest.
  select lm.*
  into v_manifest
  from public.load_manifests lm
  where lm.tenant_id = p_tenant_id
    and lm.barcode_token = p_barcode_token
  for update;

  if not found then
    raise exception 'Load manifest was not found.'
      using errcode = 'P0002';
  end if;

  if v_manifest.driver_id <> p_driver_id then
    raise exception 'This load manifest is assigned to another driver.'
      using errcode = '42501';
  end if;

  if v_manifest.vehicle_id <> p_vehicle_id then
    raise exception 'This load manifest is assigned to another vehicle.'
      using errcode = '42501';
  end if;

  -- Revalidate the active vehicle assignment inside the same transaction
  -- as the custody event.
  select
    count(*)::integer,
    count(*) filter (
      where va.vehicle_id = p_vehicle_id
    )::integer
  into
    v_active_assignment_count,
    v_matching_assignment_count
  from public.vehicle_assignments va
  where va.tenant_id = p_tenant_id
    and va.driver_id = p_driver_id
    and va.active = true;

  if v_active_assignment_count = 0 then
    raise exception 'No active vehicle is assigned to this driver.'
      using errcode = '23514';
  end if;

  if v_active_assignment_count <> 1
     or v_matching_assignment_count <> 1 then
    raise exception 'The driver active vehicle assignment does not match this load manifest.'
      using errcode = '23514';
  end if;

  -- A manifest becomes stale if Planning reassigns an included job.
  if exists (
    select 1
    from public.load_manifest_items lmi
    left join public.jobs j
      on j.id = lmi.job_id
     and j.tenant_id = p_tenant_id
    where lmi.tenant_id = p_tenant_id
      and lmi.manifest_id = v_manifest.id
      and (
        j.id is null
        or j.driver_id is distinct from p_driver_id
        or j.vehicle_id is distinct from p_vehicle_id
      )
  ) then
    raise exception 'This load manifest is stale because one or more jobs have been reassigned.'
      using errcode = '23514';
  end if;

  if not exists (
    select 1
    from public.load_manifest_items lmi
    where lmi.tenant_id = p_tenant_id
      and lmi.manifest_id = v_manifest.id
  ) then
    raise exception 'This load manifest contains no serialized items.'
      using errcode = '23514';
  end if;

  if p_stop_id is not null then
    perform 1
    from public.job_stops js
    join public.load_manifest_items lmi
      on lmi.manifest_id = v_manifest.id
     and lmi.tenant_id = p_tenant_id
     and lmi.job_id = js.job_id
    where js.id = p_stop_id
      and js.tenant_id = p_tenant_id
    limit 1;

    if not found then
      raise exception 'The supplied stop does not belong to this load manifest.'
        using errcode = '23514';
    end if;
  end if;

  select lse.event_type
  into v_latest_event_type
  from public.load_scan_events lse
  where lse.tenant_id = p_tenant_id
    and lse.manifest_id = v_manifest.id
  order by lse.scanned_at desc, lse.id desc
  limit 1;

  if p_action = 'load' then
    if v_latest_event_type = 'loaded' then
      raise exception 'This load is already on the van.'
        using errcode = 'P0001';
    end if;

    v_event_type := 'loaded';
  else
    if v_latest_event_type is null then
      raise exception 'This load has not been scanned onto the van.'
        using errcode = 'P0001';
    end if;

    if v_latest_event_type = 'unloaded' then
      raise exception 'This load has already been scanned off the van.'
        using errcode = 'P0001';
    end if;

    v_event_type := 'unloaded';
  end if;

  insert into public.load_scan_events (
    tenant_id,
    manifest_id,
    event_type,
    vehicle_id,
    driver_id,
    stop_id,
    scanned_by,
    latitude,
    longitude,
    accuracy_m
  )
  values (
    p_tenant_id,
    v_manifest.id,
    v_event_type,
    p_vehicle_id,
    p_driver_id,
    p_stop_id,
    p_scanned_by,
    p_latitude,
    p_longitude,
    p_accuracy_m
  )
  returning
    id,
    load_scan_events.scanned_at
  into
    v_event_id,
    v_scanned_at;

  select count(*)::integer
  into v_item_count
  from public.load_manifest_items lmi
  where lmi.tenant_id = p_tenant_id
    and lmi.manifest_id = v_manifest.id;

  select count(distinct lmi.job_id)::integer
  into v_job_count
  from public.load_manifest_items lmi
  where lmi.tenant_id = p_tenant_id
    and lmi.manifest_id = v_manifest.id;

  return query
  select
    v_manifest.id,
    v_manifest.manifest_number,
    v_event_id,
    v_event_type,
    v_event_type,
    v_item_count,
    v_job_count,
    v_scanned_at;
end;
$function$;


-- SECURITY DEFINER functions must not inherit PostgreSQL's default PUBLIC
-- execution permission. Only the server-side service role may execute them.
revoke all on function public.create_load_manifest(
  uuid,
  uuid,
  uuid,
  uuid,
  jsonb
) from public;

revoke all on function public.create_load_manifest(
  uuid,
  uuid,
  uuid,
  uuid,
  jsonb
) from anon;

revoke all on function public.create_load_manifest(
  uuid,
  uuid,
  uuid,
  uuid,
  jsonb
) from authenticated;

grant execute on function public.create_load_manifest(
  uuid,
  uuid,
  uuid,
  uuid,
  jsonb
) to service_role;


revoke all on function public.record_load_manifest_event(
  uuid,
  uuid,
  uuid,
  uuid,
  uuid,
  text,
  uuid,
  double precision,
  double precision,
  double precision
) from public;

revoke all on function public.record_load_manifest_event(
  uuid,
  uuid,
  uuid,
  uuid,
  uuid,
  text,
  uuid,
  double precision,
  double precision,
  double precision
) from anon;

revoke all on function public.record_load_manifest_event(
  uuid,
  uuid,
  uuid,
  uuid,
  uuid,
  text,
  uuid,
  double precision,
  double precision,
  double precision
) from authenticated;

grant execute on function public.record_load_manifest_event(
  uuid,
  uuid,
  uuid,
  uuid,
  uuid,
  text,
  uuid,
  double precision,
  double precision,
  double precision
) to service_role;